DROP TABLE IF EXISTS t;

CREATE TABLE t (a TEXT, b TEXT);

INSERT INTO t VALUES ( 'NY0123', 'US4567' );

INSERT INTO t VALUES ( 'AZ9437', 'GB1234' );

INSERT INTO t VALUES ( 'CA1279', 'FR5678' );

SELECT co.NAme, ss.CCode FROM
(
SELECT SUBSTR(a, 1, 2) AS State, SUBSTR(a, 3) AS SCODE,
SUBSTR(b, 1, 2) AS Country, SUBSTR(b, 3) AS CCode FROM t
) 
AS ss
JOIN Country AS co
ON co.Code2 = ss.Country;